### ISSUE TITLE
rakefile

### ISSUE THREAD

**Issue by shawngraham** [hepplerj/notebook#1]
Hi Jason,

This is very cool - thank you for sharing! I've installed this locally, and am now playing with the rake file. I ran `rake draft` to make a new draft, but got the error message, location doesn't exist. So I made a new folder, `_drafts`, but the error persists. I'm pretty new to Jekyll... wondered your thoughts?

```
(in /Users/shawngraham/Github/smgprojectsnotebook)
What is the title of your post? forking
Creating new draft: _drafts/forking.md
rake aborted!
Errno::ENOENT: No such file or directory @ rb_sysopen - _drafts/forking.md
/Users/shawngraham/Github/smgprojectsnotebook/Rakefile:104:in `initialize'
/Users/shawngraham/Github/smgprojectsnotebook/Rakefile:104:in `open'
/Users/shawngraham/Github/smgprojectsnotebook/Rakefile:104:in `block in <top (required)>'
Tasks: TOP => draft
```

?

**Comment by shawngraham** [comment]
Silly me. Once I moved the _drafts folder out of _source all was fine.

**Comment by shawngraham** [comment]
ok, so to get the `rake draft` etc to work, the `_drafts` folder has to be at the same level as `source`; but for `rake publish`, the code wants `_drafts` to be _inside_ `source`. So I changed line 152 like so:

`FileUtils.mv("#{DRAFTS}/#{filename}", "source/#{POSTS}/#{DATE}-#{filename}")`

and all is now tickety boo. This is my first experience working with rake files; very cool stuff you have here.

**Comment by hepplerj** [comment]
Thanks! And thanks for pointing that out -- I've had to fix that in my Rakefile also, I just forgot to when I moved everything into the `source` folder.

**Comment by shawngraham** [comment]
I don't suppose you know how to get a rakefile to do a git commit & sync in a different folder? ie, oddly enough, I'm pushing to a different repo than the one in which I'm making all my changes.

**Comment by hepplerj** [comment]
Hmm. You might be able to by messing with the `--git-dir` and `--working-tree` switches: http://stackoverflow.com/questions/22691575/run-git-commit-from-another-directory
